# Generated by Django 5.0.4 on 2024-05-03 12:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('image_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='تصویر اصلی مقاله')),
                ('short_text', models.TextField(verbose_name='متن خلاصه مقاله')),
                ('text', models.TextField(verbose_name='متن مقاله')),
                ('key_words', models.CharField(max_length=200, verbose_name='کلمات کلیدی')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ درج مقاله')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار مقاله')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='تاریخ آخرین ویرایش مقاله')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('pdf_file_name', models.CharField(max_length=200, verbose_name='فایل pdf مقاله')),
                ('view_number', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
                'db_table': 't_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100, verbose_name='عنوان گروه مقالات')),
            ],
            options={
                'verbose_name': 'گروه مقاله',
                'verbose_name_plural': 'گروه مقاله ها',
                'db_table': 't_article_group',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='ایمیل')),
                ('mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تماس')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندکان',
                'db_table': 't_author',
            },
        ),
        migrations.CreateModel(
            name='ArticleGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200, verbose_name='نام تصویر')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='گروه مقاله')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'db_table': 't_article_galery',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articlegroup', verbose_name='گروه مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='articles.author', verbose_name='نویسنده مقاله ها'),
        ),
    ]
