# Generated by Django 5.0.4 on 2024-05-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemoryGalery',
            new_name='MemoryGallery',
        ),
    ]
